version: "3.9"
services:

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m

  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    restart: on-failure
    logging:
      options:
        max-size: 10m

volumes:
  db-data: {}

networks:
  public:
  private:
    driver: bridge
    internal: true
